AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lamda demo
  
Resources:
  writeUser:
    Type: AWS::Serverless::Function 
    Properties:
      Timeout: 10
      CodeUri: ./ # format is projectPath/
      Handler: writeUserLambda.handler # format is filename.functionName
      Runtime: nodejs16.x